### ISSUE TITLE
RE-AMT code not found

### ISSUE THREAD

**Issue by JUJUEZAIWAN** [synlp/.github#1]
I want to follow  up on your work 《Enhancing Relation Extraction via Adversarial Multi-task Learning》 on LREC 2022, but the source code url （https://github.com/synlp/RE-AMT） in your paper is not accessible. So can you open source this work?

**Comment by yuanheTian** [comment]
> I want to follow up on your work 《Enhancing Relation Extraction via Adversarial Multi-task Learning》 on LREC 2022, but the source code url （[https://github.com/synlp/RE-AMT）](https://github.com/synlp/RE-AMT%EF%BC%89) in your paper is not accessible. So can you open source this work?

The code should be available now. :)
