### ISSUE TITLE
Request for "Aspect-based Sentiment Analysis with Context Denoising" code

### ISSUE THREAD

**Issue by ccflyu** [synlp/.github#4]
I recently read a published paper titled "Aspect-based Sentiment Analysis with Context Denoising."

I noticed that the link to the code repository mentioned in the paper leads to a 404 error.The link is " https://github.com/synlp/ASA-CD".I would greatly appreciate it if you could share the code or provide an alternative link to access it.

 I look forward to your reply.

**Comment by fang-kun** [comment]
Hello, have you now gotten the code for this paper?

**Comment by yuanheTian** [comment]
Thank you for your interest in our work. Because the code is currently being used for commercial purposes, we’re unable to release it at this time. We will make it available as soon as we can.
